# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=100)),
                ('item_icon', models.CharField(max_length=100)),
                ('item_desc', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_date', '-updated'],
            },
        ),
    ]
