# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 11:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 8, 7, 11, 3, 48, 18201, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
